# Generated by Django 4.0.2 on 2022-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0002_order_address_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(4, 'Odebrane'), (1, 'Zamówione'), (3, 'Wysłane'), (2, 'Opłacone')]),
        ),
    ]
