# Generated by Django 4.0.2 on 2022-02-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0005_product_slug_alter_order_state_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3),
        ),
    ]
