# Generated by Django 4.0.2 on 2022-02-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0007_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_method',
            field=models.CharField(choices=[('poczta', 'PocztaPolska'), ('paczkomat', 'Paczkomat Inpost'), ('DPD', 'Kurier DPD')], default='paczkomat', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BLIK', 'Płatność BLIK'), ('przelew', 'Przelew interentowy'), ('pobranie', 'Za pobraniem')], default='BLIK', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(3, 'Wysłane'), (4, 'Odebrane'), (2, 'Opłacone'), (1, 'Zamówione')], default=1),
        ),
    ]
