# Generated by Django 4.0.2 on 2022-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0008_order_deliver_method_order_full_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_method',
            field=models.CharField(choices=[('paczkomat', 'Paczkomat Inpost'), ('poczta', 'PocztaPolska'), ('DPD', 'Kurier DPD')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pobranie', 'Za pobraniem'), ('przelew', 'Przelew interentowy'), ('BLIK', 'Płatność BLIK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Zamówione'), (2, 'Opłacone'), (3, 'Wysłane'), (4, 'Odebrane')], default=1),
        ),
    ]
