# Generated by Django 4.0.2 on 2022-02-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0009_alter_order_deliver_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_method',
            field=models.CharField(choices=[('poczta', 'Poczta Polska'), ('DPD', 'Kurier DPD'), ('paczkomat', 'Paczkomat Inpost')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pobranie', 'Za pobraniem'), ('przelew', 'Przelew internetowy'), ('BLIK', 'Płatność BLIK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(3, 'Wysłane'), (1, 'Zamówione'), (4, 'Odebrane'), (2, 'Opłacone')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szalonebembeny.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='głosy'),
        ),
    ]
