# Generated by Django 4.0.4 on 2023-06-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szalonebembeny', '0011_product_imgpath_alter_order_deliver_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_method',
            field=models.CharField(choices=[('paczkomat', 'Paczkomat Inpost'), ('DPD', 'Kurier DPD'), ('poczta', 'Poczta Polska')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BLIK', 'Płatność BLIK'), ('przelew', 'Przelew internetowy'), ('pobranie', 'Za pobraniem')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(3, 'Wysłane'), (1, 'Zamówione'), (2, 'Opłacone'), (4, 'Odebrane')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, to='szalonebembeny.product'),
        ),
    ]
